<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="<?php echo $this->getUrl("*/*/loginPost")?>" method = "post">    
        <label for = "username">User Name:</label>
        <input type="text" name = 'login[user]'>
        <label for="password">Password</label>
        <input type="password" name = 'login[password]'>
        <button>Login</button>        
    </form>
</body>
</html>