<!DOCTYPE html>
<html lang="en">

<head>
   
            <?php $this->getChildHtml('head');?>
    
</head>

<body>
    <div class="html">
    <!-- <div class = "head">
            <? // php $this->getChildHtml('head');?>
        </div> -->
        <div class="header">
            <?php $this->getChildHtml('header'); ?>
        </div>
        <div class="message">
            <?php $this->getChildHtml('message'); ?>
        </div>
        <div class="content">
            <?php $this->getChildHtml('content'); ?>
        </div>
        <div class="footer">
            <?php $this->getChildHtml('footer'); ?>
        </div>
    </div>
</body>

</html>